### ISSUE TITLE
etherpad import fails in v3.0.1

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/portal#160]
Hi,
I have installed v3.0.1 and I tried to import an etherpad instance from v2.6.

I got this error, and now etherpad is not running anymore:

E, [2018-12-28 20:26:04 #642] ERROR -- : undefined method `[]' for nil:NilClass
E, [2018-12-28 20:26:04 #642] ERROR -- :   /root/portal/lib/routes/mazi_config.rb:216:in `block in registered'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
E, [2018-12-28 20:26:04 #642] ERROR -- :   /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:148:in `start'
E, [2018-12-28 20:26:04 #642] ERROR -- :   mazi_portal_server.rb:181:in `'

**Comment by panosnethood** [comment]
In another fresh installation this worked, so perhaps there is a combination of actions that causes the error. I will explore more and report if I will manage to reproduce it again.

**Comment by haniavis** [comment]
I just did the procedure and it went well with no errors. The only thing is that I had to manually restart Etherpad (I did it through the admin panel) to see the imported pads.
